FROM node
# Create app directory
WORKDIR /app
# Install app dependencies
COPY /package.json ./
COPY /yarn.lock ./

# RUN npm install -g yarn
# RUN ["apt-get", "update"]
# RUN ["apt-get", "install", "-y", "vim"]
RUN yarn install --network-timeout 1000000 
# Copy app source code
COPY . .

#Expose port and start applicationa
CMD ["yarn", "start"]