language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t crimes-new-dashboard .
after_success:
    - docker build -t cirmes-new-dashboard/crimes-client ./crimes-client
    - docker build -t cirmes-new-dashboard/backend ./backend
    - docker build -t cirmes-new-dashboard/crime_data_explorer ./crime_data_explorer
    - docker build -t cirmes-new-dashboard/nginx ./nginx


deploy:
    provider: elasticbeanstalk
    region: ap-south-1
    app: "crimes-cleint"
    env: CrimesCleint-env
    bucket_name: elasticbeanstalk-ap-south-1-327828610480
    bucket_path: "crimes-cleint"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"

        




