language: generic
sudo: required
services:
    - docker
# before_install:
#     - docker build -t crimes-new-dashboard .
after_success:
    - docker build -t sunpausiddharth/crimes-new-dashboard-copy-crimes-client ./crimes-client
    - docker build -t sunpausiddharth/crimes-new-dashboard-copy-backend ./backend
    - docker build -t sunpausiddharth/crimes-new-dashboard-copy-crime_data_explorer ./crime_data_explorer
    - docker build -t sunpausiddharth/crimes-new-dashboard-copy-nginx ./nginx
    # - docker build -t sunpausiddharth/crimes-new-dashboard-copy-database ./fiiles
    # - docker build -t sunpausiddharth/crimes-new-dashboard-copy-fiiles ./fiiles
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push sunpausiddharth/crimes-new-dashboard-copy-crimes-client
    - docker push sunpausiddharth/crimes-new-dashboard-copy-backend
    - docker push sunpausiddharth/crimes-new-dashboard-copy-crime_data_explorer
    - docker push sunpausiddharth/crimes-new-dashboard-copy-nginx
    # - docker push sunpausiddharth/crimes-new-dashboard-copy-database


deploy:
    provider: elasticbeanstalk
    region: ap-south-1
    app: "crimes-new-dashboard"
    env: CrimesNewDashboard-env 
    bucket_name: elasticbeanstalk-ap-south-1-209500048126
    bucket_path: "crimes-new-dashboard"
    edge: true
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"

        




