version: '3.0'
services:
    crimes-client:
        build:
            dockerfile: Dockerfile.dev # specify the directory of the Dockerfile
            context: ./crimes-client
    
    nginx:
        build:
            dockerfile: Dockerfile.dev # specify the directory of the Dockerfile
            context: ./nginx
        restart: always  
        ports:
            - 3050:80 #specify ports mapping
        depends_on: 
            - crimes-client
            - backend
            - crime_data_explorer
        
 
    backend: # name of the second service
        build:
            dockerfile: Dockerfile.dev # specify the directory of the Dockerfile
            context: ./backend
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379

    crime_data_explorer: # name of the second service
        build:
            dockerfile: Dockerfile.dev # specify the directory of the Dockerfile
            context: ./crime_data_explorer

    database: # name of the third service
        image: mongo # specify image to build container from
        ports:
            - 27017:27017 # specify port forwarding
        restart: always
    
    redis:
        image: "redis:latest"