var mongoose = require('mongoose');

var ArrestsNationalAdultSchema = new mongoose.Schema({
    "id": String,
    "state_abbr": String,
    "year": Number,
    "offense_code": String,
    "offense_name": String,
    "agencies": Number,
    "population": Number,
    "total_male": Number,
    "total_female": Number,
    "m_18": Number,
    "m_19": Number,
    "m_20": Number,
    "m_21": Number,
    "m_22": Number,
    "m_23": Number,
    "m_24": Number,
    "m_25_29": Number,
    "m_30_34": Number,
    "m_35_39": Number,
    "m_40_44": Number,
    "m_45_49": Number,
    "m_50_54": Number,
    "m_55_59": Number,
    "m_60_64": Number,
    "m_65p": Number,
    "f_18": Number,
    "f_19": Number,
    "f_20": Number,
    "f_21": Number,
    "f_22": Number,
    "f_23": Number,
    "f_24": Number,
    "f_25_29": Number,
    "f_30_34": Number,
    "f_35_39": Number,
    "f_40_44": Number,
    "f_45_49": Number,
    "f_50_54": Number,
    "f_55_59": Number,
    "f_60_64": Number,
    "f_65p": Number,
    "race_agencies": Number,
    "race_population": Number,
    "white": Number,
    "black": Number,
    "asian_pacific_islander": Number,
    "american_indian": Number
});
mongoose.model('arrests_national_adult', ArrestsNationalAdultSchema);

module.exports = mongoose.model('arrests_national_adult');