var mongoose = require('mongoose');

var SupplementalStateSchema = new mongoose.Schema({  
    clothing_and_furs:Number,
    clothing_and_furs_recovered_count:Number,
    clothing_and_furs_stolen_value:Number,
    consumable_goods:Number,
    consumable_goods_recovered_count:Number,
    consumable_goods_stolen_value:Number,
    currency_notes_etc:Number,
    currency_notes_etc_recovered_count:Number,
    currency_notes_etc_stolen_value:Number,
    data_year:Number,
    firearms:Number,
    firearms_recovered_count:Number,
    firearms_stolen_value:Number,
    household_goods:Number,
    household_goods_recovered_count:Number,
    household_goods_stolen_value:Number,
    jewelry_and_precious_metals:Number,
    jewelry_and_precious_metals_recovered_count:Number,
    jewelry_and_precious_metals_stolen_value:Number,
    livestock:Number,
    livestock_recovered_count:Number,
    livestock_stolen_value:Number,
    locally_stolen_motor_vehicles:Number,
    locally_stolen_motor_vehicles_recovered_count:Number,
    locally_stolen_motor_vehicles_stolen_value:Number,
    miscellaneous:Number,
    miscellaneous_recovered_count:Number,
    miscellaneous_stolen_value:Number,
    not_specified:Number,
    not_specified_recovered_count:Number,
    not_specified_stolen_value:Number,
    office_equipment:Number,
    office_equipment_recovered_count:Number,
    office_equipment_stolen_value:Number,
    telvisions_radio_stereos_etc:Number,
    telvisions_radio_stereos_etc_recovered_count:Number,
    telvisions_radio_stereos_etc_stolen_value:Number,
});
mongoose.model('supplemental_state', SupplementalStateSchema);

module.exports = mongoose.model('supplemental_state');